version: '3.5'

services:
  
  <env>-contactrh-mongo:
    image: "149.202.64.71:5001/mongo:3.4.15"
    deploy:
      replicas: 1
    ports:
      - "27100:27017"
    volumes:
      - "<env>_contactrh_mongo_data:/data"
    networks:
      - <env>

  <env>-contacrh-api:
    image: "149.202.64.71:5001/innovation/contactrh:<revision_git>"  
    deploy:
      replicas: 1
    links:
      - <env>-contactrh-mongo:mongo
    ports:
      - "::8000"
    labels:
      - "traefik.port=8000"
      - "traefik.backend=<env>-contacrh-api"
      - "traefik.frontend.rule=PathPrefix: /<env>/contactrh-api"
      - "traefik.docker.network=<env>"
      - "application.name=contactrh"
      - "application.version=1.0"
    networks:
      - <env>

networks:
  <env>:
    driver: overlay
    external: true
    name: <env>

volumes:
  <env>_contactrh_mongo_data:
  
